from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ControlMetadata:
    control_id: str
    target: str
    intent: str
    apply_behavior: str
    nist_csf: tuple[str, ...]
    iso_27001: tuple[str, ...]
    cis: str

    @property
    def help_uri(self) -> str:
        return f"https://wahidhendrawan.github.io/Automation-Hardening/controls.html#{self.control_id.lower()}"


CONTROL_METADATA: dict[str, ControlMetadata] = {
    item.control_id: item
    for item in [
        ControlMetadata(
            "AWS-ORG-001",
            "AWS account",
            "Confirm each organization member account is assessable",
            "Report only",
            ("ID.AM",),
            ("5.9",),
            "AWS Foundations - Inventory",
        ),
        ControlMetadata(
            "AWS-ORG-CONFIG-001",
            "AWS organization",
            "Confirm organization-wide Config aggregation",
            "Report only",
            ("DE.CM", "PR.PS"),
            ("8.9", "8.15"),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-ORG-CT-001",
            "AWS organization",
            "Confirm organization CloudTrail logging",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "AWS Foundations - Logging",
        ),
        ControlMetadata(
            "AWS-ORG-GD-001",
            "AWS organization",
            "Confirm GuardDuty delegated administration",
            "Report only",
            ("DE.CM",),
            ("8.16",),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-ORG-SH-001",
            "AWS organization",
            "Confirm Security Hub delegated administration",
            "Report only",
            ("DE.CM",),
            ("8.16",),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-S3-001",
            "AWS account",
            "Block public S3 access at account level",
            "Enables all four settings",
            ("PR.DS",),
            ("8.3", "8.9"),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-002",
            "S3 bucket",
            "Reject public ACL grants",
            "Report only",
            ("PR.AA", "PR.DS"),
            ("5.15", "8.3"),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-003",
            "S3 bucket",
            "Reject public bucket policies",
            "Report only",
            ("PR.AA", "PR.DS"),
            ("5.15", "8.3"),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-004",
            "S3 bucket",
            "Block public access at bucket level",
            "Enables all four settings",
            ("PR.DS",),
            ("8.3", "8.9"),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-005",
            "S3 bucket",
            "Enable default encryption",
            "Enables SSE-S3",
            ("PR.DS",),
            ("8.24",),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-006",
            "S3 bucket",
            "Enable versioning",
            "Enables versioning",
            ("PR.DS",),
            ("8.13",),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-S3-007",
            "S3 bucket",
            "Configure server access logging",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "AWS Foundations - Logging",
        ),
        ControlMetadata(
            "AWS-IAM-001",
            "AWS account",
            "Require root-user MFA",
            "Report only",
            ("PR.AA",),
            ("5.17",),
            "AWS Foundations - IAM",
        ),
        ControlMetadata(
            "AWS-IAM-002",
            "AWS region",
            "Enable IAM Access Analyzer",
            "Creates account analyzer",
            ("PR.AA", "DE.CM"),
            ("5.15", "8.16"),
            "AWS Foundations - IAM",
        ),
        ControlMetadata(
            "AWS-CT-001",
            "AWS account",
            "Keep a multi-region CloudTrail trail logging",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "AWS Foundations - Logging",
        ),
        ControlMetadata(
            "AWS-CONFIG-001",
            "AWS region",
            "Enable AWS Config recording",
            "Report only",
            ("DE.CM", "PR.PS"),
            ("8.9", "8.15"),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-GD-001",
            "AWS region",
            "Enable GuardDuty",
            "Report only",
            ("DE.CM",),
            ("8.16",),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-SH-001",
            "AWS region",
            "Enable Security Hub",
            "Report only",
            ("DE.CM",),
            ("8.16",),
            "AWS Foundations - Monitoring",
        ),
        ControlMetadata(
            "AWS-EC2-001",
            "AWS region",
            "Remove rules from default security groups",
            "Report only",
            ("PR.IR",),
            ("8.20",),
            "AWS Foundations - Networking",
        ),
        ControlMetadata(
            "AWS-EBS-001",
            "AWS region",
            "Enable EBS encryption by default",
            "Enables account-region setting",
            ("PR.DS",),
            ("8.24",),
            "AWS Foundations - Storage",
        ),
        ControlMetadata(
            "AWS-RDS-001",
            "AWS region",
            "Encrypt RDS DB instance storage",
            "Report only",
            ("PR.DS",),
            ("8.24",),
            "AWS Foundations - Database",
        ),
        ControlMetadata(
            "AWS-VPC-001",
            "AWS region",
            "Enable VPC Flow Logs for every VPC",
            "Creates Flow Logs when policy destination is set",
            ("DE.CM",),
            ("8.15",),
            "AWS Foundations - Networking",
        ),
        ControlMetadata(
            "AWS-KMS-001",
            "AWS region",
            "Rotate eligible customer-managed keys",
            "Report only",
            ("PR.DS",),
            ("8.24",),
            "AWS Foundations - Cryptography",
        ),
        ControlMetadata(
            "AZURE-IAM-001",
            "Azure",
            "Discover assessable subscriptions",
            "Report only",
            ("PR.AA",),
            ("5.15",),
            "Microsoft Azure Foundations - Identity",
        ),
        ControlMetadata(
            "AZURE-STORAGE-001",
            "Azure",
            "Enforce HTTPS and modern TLS for Storage",
            "Report only",
            ("PR.DS",),
            ("8.24",),
            "Microsoft Azure Foundations - Storage",
        ),
        ControlMetadata(
            "AZURE-STORAGE-002",
            "Azure",
            "Default Storage network access to deny",
            "Report only",
            ("PR.IR",),
            ("8.20",),
            "Microsoft Azure Foundations - Storage",
        ),
        ControlMetadata(
            "AZURE-KV-001",
            "Azure",
            "Restrict Key Vault public network access",
            "Report only",
            ("PR.IR", "PR.DS"),
            ("8.20", "8.24"),
            "Microsoft Azure Foundations - Key Vault",
        ),
        ControlMetadata(
            "AZURE-SQL-001",
            "Azure",
            "Enable Azure SQL server auditing",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "Microsoft Azure Foundations - Database",
        ),
        ControlMetadata(
            "AZURE-NET-001",
            "Azure",
            "Restrict internet-exposed administrative ports",
            "Report only",
            ("PR.IR",),
            ("8.20",),
            "Microsoft Azure Foundations - Networking",
        ),
        ControlMetadata(
            "AZURE-SEC-001",
            "Azure",
            "Enable Defender for Cloud plans",
            "Report only",
            ("DE.CM",),
            ("8.16",),
            "Microsoft Azure Foundations - Security",
        ),
        ControlMetadata(
            "AZURE-LOG-001",
            "Azure",
            "Export subscription activity logs",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "Microsoft Azure Foundations - Logging",
        ),
        ControlMetadata(
            "AZURE-LOG-002",
            "Azure",
            "Configure modern diagnostic settings",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "Microsoft Azure Foundations - Logging",
        ),
        ControlMetadata(
            "GCP-IAM-001",
            "GCP",
            "Discover assessable projects",
            "Report only",
            ("PR.AA",),
            ("5.15",),
            "Google Cloud Foundations - Identity",
        ),
        ControlMetadata(
            "GCP-IAM-002",
            "GCP",
            "Remove user-managed service-account keys",
            "Report only",
            ("PR.AA",),
            ("5.16", "5.17"),
            "Google Cloud Foundations - Identity",
        ),
        ControlMetadata(
            "GCP-STORAGE-001",
            "GCP",
            "Reject public Cloud Storage IAM",
            "Report only",
            ("PR.AA", "PR.DS"),
            ("5.15", "8.3"),
            "Google Cloud Foundations - Storage",
        ),
        ControlMetadata(
            "GCP-STORAGE-002",
            "GCP",
            "Enable uniform bucket-level access",
            "Report only",
            ("PR.AA",),
            ("5.15",),
            "Google Cloud Foundations - Storage",
        ),
        ControlMetadata(
            "GCP-KMS-001",
            "GCP",
            "Rotate Cloud KMS keys",
            "Report only",
            ("PR.DS",),
            ("8.24",),
            "Google Cloud Foundations - Cryptography",
        ),
        ControlMetadata(
            "GCP-NET-001",
            "GCP",
            "Restrict internet-exposed administrative ports",
            "Report only",
            ("PR.IR",),
            ("8.20",),
            "Google Cloud Foundations - Networking",
        ),
        ControlMetadata(
            "GCP-LOG-001",
            "GCP",
            "Configure centralized logging sinks",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "Google Cloud Foundations - Logging",
        ),
        ControlMetadata(
            "GCP-LOG-002",
            "GCP",
            "Enable project audit logging",
            "Report only",
            ("DE.CM",),
            ("8.15",),
            "Google Cloud Foundations - Logging",
        ),
        ControlMetadata(
            "GCP-SEC-001",
            "GCP",
            "Review Security Command Center posture",
            "Manual",
            ("DE.CM",),
            ("8.16",),
            "Google Cloud Foundations - Monitoring",
        ),
        ControlMetadata(
            "LINUX-FW-001",
            "Linux",
            "Enable a host firewall",
            "Enables UFW/firewalld",
            ("PR.IR",),
            ("8.20",),
            "CIS Linux Benchmarks - Host Firewall",
        ),
        ControlMetadata(
            "LINUX-SSH-001",
            "Linux",
            "Disable SSH root login",
            "Updates and validates sshd config",
            ("PR.AA",),
            ("5.15", "5.17"),
            "CIS Linux Benchmarks - SSH",
        ),
        ControlMetadata(
            "LINUX-SSH-002",
            "Linux",
            "Disable SSH empty passwords",
            "Updates and validates sshd config",
            ("PR.AA",),
            ("5.17",),
            "CIS Linux Benchmarks - SSH",
        ),
        ControlMetadata(
            "LINUX-PATCH-001",
            "Linux",
            "Apply available package updates",
            "Updates packages",
            ("PR.PS",),
            ("8.8",),
            "CIS Linux Benchmarks - Patch Management",
        ),
        ControlMetadata(
            "MACOS-FW-001",
            "macOS",
            "Enable firewall and stealth mode",
            "Applies setting",
            ("PR.IR",),
            ("8.20",),
            "CIS Apple macOS Benchmark - Firewall",
        ),
        ControlMetadata(
            "MACOS-GK-001",
            "macOS",
            "Enable Gatekeeper",
            "Applies setting",
            ("PR.PS",),
            ("8.8",),
            "CIS Apple macOS Benchmark - Gatekeeper",
        ),
        ControlMetadata(
            "MACOS-PATCH-001",
            "macOS",
            "Enable scheduled update checks",
            "Applies setting",
            ("PR.PS",),
            ("8.8",),
            "CIS Apple macOS Benchmark - Updates",
        ),
        ControlMetadata(
            "MACOS-AUTH-001",
            "macOS",
            "Disable guest account",
            "Applies setting",
            ("PR.AA",),
            ("5.15",),
            "CIS Apple macOS Benchmark - Accounts",
        ),
        ControlMetadata(
            "MACOS-DISK-001",
            "macOS",
            "Enable FileVault",
            "Manual due to key escrow requirements",
            ("PR.DS",),
            ("8.24",),
            "CIS Apple macOS Benchmark - FileVault",
        ),
        ControlMetadata(
            "WINDOWS-FW-001",
            "Windows",
            "Enable firewall profiles",
            "Applies setting",
            ("PR.IR",),
            ("8.20",),
            "CIS Microsoft Windows Benchmarks - Firewall",
        ),
        ControlMetadata(
            "WINDOWS-SMB-001",
            "Windows",
            "Disable SMBv1",
            "Disables optional feature",
            ("PR.PS",),
            ("8.8", "8.9"),
            "CIS Microsoft Windows Benchmarks - Network Protocols",
        ),
        ControlMetadata(
            "WINDOWS-AUTH-001",
            "Windows",
            "Disable RID-501 guest account",
            "Applies setting",
            ("PR.AA",),
            ("5.15",),
            "CIS Microsoft Windows Benchmarks - Accounts",
        ),
        ControlMetadata(
            "WINDOWS-AUDIT-001",
            "Windows",
            "Enable logon and process auditing",
            "Applies setting",
            ("DE.CM",),
            ("8.15",),
            "CIS Microsoft Windows Benchmarks - Audit Policy",
        ),
    ]
}
