version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      aws:
        patterns: ["boto3*"]
      azure:
        patterns: ["azure-*"]
      gcp:
        patterns: ["google-*"]
      k8s:
        patterns: ["kubernetes*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
